### ISSUE TITLE
Use within Angular material forms causes validation errors

### ISSUE THREAD

**Issue by Enngage** [selvera/npm-datepicker#10]
This one might a bit tricky - the problem is that if you use your version of `mat-datepicker`, the validation of this field will fail if its used inside `mat-form-field` and if the field is required. This is likely connected to https://github.com/angular/material2/issues/9619 and using custom validation might be a solution in this case. 

See snapshot:

![ab](https://user-images.githubusercontent.com/7137351/42137048-e85b9aea-7d65-11e8-8219-40cc163b9d41.png)

Thanks!

**Comment by matheo** [comment]
@Enngage yeah, yesterday I introduced an error validating the parsed value from the input, but now it's fixed in `0.9.4`. I just released it with some style fixes. Looking forward for your feedback ;)

**Comment by Enngage** [comment]
Thank you! I can confirm it works now :-)
