### ISSUE TITLE
Incorrect colon size

### ISSUE THREAD

**Issue by Enngage** [selvera/npm-datepicker#12]
The colon size (between hours & minutes) is quite large as it inherits 32px:

![bb](https://user-images.githubusercontent.com/7137351/42159439-0880ce24-7df4-11e8-89c0-367655c501e8.png)
I can fix this with:

```
.mat-calendar-header-time-hour {
    font-size: 12px!important;
}
```

**Comment by matheo** [comment]
@Enngage seems lilke a conflict between the styles of your `button` with the `datepicker-controls`. The `12` `28` needs to be bigger there, so I added the complete SCSS path to avoid conflicts with the styles of the app.

Try `0.9.5` please ;)

**Comment by matheo** [comment]
@Enngage did it work?
