### ISSUE TITLE
mat-datepicker not a known element

### ISSUE THREAD

**Issue by kclercR310** [selvera/npm-datepicker#20]
Hey guys.
I have some trouble to get this package to work.

I have some lazy loaded modules in which I want to use the datepicker.
I added the imports of the modules into the core module.
Do I have to add something also in the Lazy modules to get this to work?

The error says that `ERROR in : 'mat-datepicker' is not a known element:`.

Any help very appreciated

**Comment by matheo** [comment]
@kclercR310 be sure to import the `MatDatepickerModule` and `MatMomentDateModule` in your lazy NgModule: https://github.com/selvera/npm-datepicker#installation
