### ISSUE TITLE
Wrong number of argument for theme in Angular material 7.0.0-beta.2

### ISSUE THREAD

**Issue by Enngage** [selvera/npm-datepicker#21]
#### Bug Report

After upgrading to Angular material `7.0.0-beta.2` we encounter following exception when building the app:

```
ERROR in ./trainer/assets/material/material-theme.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./trainer/assets/material/material-theme.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
          ^
      Wrong number of arguments (3 for 1) for `mat-elevation'
      in c:\dev\FitRockApp\node_modules\@angular\material\_theming.scss (line 447, column 12)
ERROR in ./trainer/assets/theme/main.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./trainer/assets/theme/main.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
          ^
      Wrong number of arguments (3 for 1) for `mat-elevation'
      in c:\dev\FitRockApp\node_modules\@angular\material\_theming.scss (line 447, column 12)
```

This is caused by only importing covalent theme in our theming sass file:

`@import '~@coachcare/datepicker/theming';`

This is likely related to the fact that mat-elevation has been removed from the stylesheet as mentioned in [release notes for 7.0.0-beta.2](https://github.com/angular/material2/releases/tag/7.0.0-beta.2)

Thank you!

**Comment by Enngage** [comment]
Hi, thanks for a quick response! Yeah, it seems to be working now :) 

Could you please take a look at the https://github.com/selvera/npm-datepicker/issues/17 as well? this is kind of important for 24 hour format selection.

**Comment by matheo** [comment]
@Enngage yeah, I will have a look!
thanks for the report!
