### ISSUE TITLE
RxJs 6 Support, without rxjs-compat 

### ISSUE THREAD

**Issue by f-aubert** [selvera/npm-datepicker#3]
RxJs 6 Support, without rxjs-compat is suggested.
Shouldn't be too big of a change, or?
Thanks in advance

**Comment by matheo** [comment]
@f-aubert yeah, it's not a big deal, I will try to get it done perhaps PRs are always welcome ;)

**Comment by matheo** [comment]
Fixed in `@coachcare/datepicker 0.9.2` :)

**Comment by f-aubert** [comment]
Awesome. Thanks a lot.
