### ISSUE TITLE
usage without SCSS

### ISSUE THREAD

**Issue by wmoisesd** [selvera/npm-datepicker#6]
Hello!

I am a begginer in Angular.

Can I use this date picker without SCSS in my angular project?

All style files are CSS, not SCSS

Thanks and regards.

**Comment by matheo** [comment]
@wmoisesd you're lucky!

I just added support for the Angular Material prebuilt themes (CSS)
and added some lines on the README to see the available alternatives:
https://github.com/selvera/npm-datepicker#styling

Enjoy!
