### ISSUE TITLE
Custom translations

### ISSUE THREAD

**Issue by Enngage** [selvera/npm-datepicker#8]
Hi, is there a way to translate 'OK' & 'CANCEL' buttons? 

On a sidenote - The buttons don't have any margin between them, you might want to add some.

**Comment by matheo** [comment]
You can provide your own `MatDatepickerIntl`:
https://material.angular.io/components/datepicker/overview#localizing-labels-and-messages

following this interface:
https://github.com/selvera/npm-datepicker/blob/master/datepicker/src/lib/datepicker-intl.ts#L12

and yeah, I have to fix those margins! :)

**Comment by Enngage** [comment]
Thank you! The 'submit' label is missing from their documentation page and
I didn't know it existed :-)

**Comment by matheo** [comment]
@Enngage It exists here because the official module doesn't confirm the selection ;)
