### ISSUE TITLE
selectedChanged is not emitted

### ISSUE THREAD

**Issue by Enngage** [selvera/npm-datepicker#9]
Using 

`<mat-datepicker (selectedChanged)="changeDate($event)" type="datetime" [twelveHour]="twelveHour" clockStep="1" #datepicker></mat-datepicker>`

Doet not trigger `changeDate` method.

**Comment by matheo** [comment]
@Enngage `MatDatepicker` deprecated that Output some versions ago, now the `MatDatepickerInput` has `dateChange` and `dateInput` outputs:
https://material.angular.io/components/datepicker/api#MatDatepickerInput
